[package]
name = "AutoShortcut"
version = "0.1.0"
edition = "2021"

[build-dependencies]
embed-resource = "1.6.5"

# 优化编译体积
[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
anyhow = "1.0.57"
vc-ltl = "5.0.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
clap = { version = "3.1.8", features = ["derive"] }
console = "0.15.0"
walkdir = "2.3.2"
mslnk = "0.1.7"
